### PR TITLE
Bug 916863: update 2.6 kernel for ARM & x86

### PR DESCRIPTION
**Pull request by vicamo**
-from commit 20785c47d2a8e9cbd7bf40698dcade00875ace06
-add goldfish nfc platform driver

### CODE REVIEW

**Comment by tdz** [comment]
Hey,

The NFC stuff is still pretty much WIP. I'm one PTO currently, but will be back next week for cleaning up things and getting them ready for merging.

**Comment by vicamo** [comment]
Update built image from https://github.com/tdz/kernel_goldfish/commit/3a9d7c641bdefd6d0905cc32c7423d9086fa497c

**Comment by vicamo** [comment]
update commit message only, no change.

**Comment by vicamo** [comment]
Update kernel image built from https://github.com/vicamo/b2g_kernel_goldfish/commit/661373c

**Pull request merged**
